name: task_11
description: "Задание — Визитка."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #spider: 4.2.2

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: PTSans
      fonts:
        - asset: assets/fonts/pt_sans/PTSans-Regular.ttf
        - asset: assets/fonts/pt_sans/PTSans-Bold.ttf
          weight: 700
